name: Man10TitlePlugin
version: '1.0-SNAPSHOT'
main: io.github.uttmangosteen.man10TitlePlugin.Main

commands:
  mtitle:
    usage: "§d=== Man10TitlePlugin help ===\n
            §d/<mtitle|mtitle_test|mtitle_all> [title] | [subTitle] | [stay(sec)] | [fadeOut(sec)]\n
            §dmtitle...鯖内, mtitle_test...自分のみ, mtitle_all...全鯖\n
            §dデフォルト stay...5, fadeOut...2\n
            §d&でカラコ#でスペース使えます\n
            §d============================="
    permission: red.man10.mtitle
  mtitle_test:
    usage: "§d=== Man10TitlePlugin help ===\n
            §d/<mtitle|mtitle_test|mtitle_all> [title] | [subTitle] | [stay(sec)] | [fadeOut(sec)]\n
            §dmtitle...鯖内, mtitle_test...自分のみ, mtitle_all...全鯖\n
            §dデフォルト stay...5, fadeOut...2\n
            §d&でカラコ#でスペース使えます\n
            §d============================="
    permission: red.man10.mtitle
  mtitle_all:
    usage: "§d=== Man10TitlePlugin help ===\n
            §d/<mtitle|mtitle_test|mtitle_all> [title] | [subTitle] | [stay(sec)] | [fadeOut(sec)]\n
            §dmtitle...鯖内, mtitle_test...自分のみ, mtitle_all...全鯖\n
            §dデフォルト stay...5, fadeOut...2\n
            §d&でカラコ#でスペース使えます\n
            §d============================="
    permission: red.man10.mtitle
permissions:
  red.man10.mtitle:
    default: op